### ISSUE TITLE
CTC sendSpeedAuth() crash

### ISSUE THREAD

**Issue by ryanpitt** [suffolk-northern/main#71]
Seems to happen rarely but randomly?

```
Exception in thread "Timer-0" java.lang.IllegalArgumentException: authority range
	at train_model.communication.TrackMovementCommand.<init>(TrackMovementCommand.java:46)
	at ctc.Ctc.sendSpeedAuth(Ctc.java:1143)
	at ctc.Ctc.updateAuth(Ctc.java:1055)
	at ctc.Ctc.updateBlock(Ctc.java:116)
	at ctc.Ctc.update(Ctc.java:62)
	at updater.Updater.iteration(Updater.java:49)
	at updater.Updater$Task.run(Updater.java:73)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by ryanpitt** [comment]
You should catch the exception and do something graceful.

**Comment by sapike** [comment]
Looks like that exception is for auth < 0 in track movement command. That’s weird, I’ll take a look. Is it on dispatch or after the train has been going for a while with no one touching the CTC UI?

**Comment by ryanpitt** [comment]
After it's been going for a while. One time, I set the train controller to 40 kph and it crashed around halfway down the first straightway. Another time at a different speed, no problem.
